### PR TITLE
added sticky wysiwyg

### LINKED ISSUE #70: WYSIWYG toolbar is not sticky by default
**Issue**

```gherkin
Given I edit a long text
When I scroll down the page
Then I can not see the WYSIWYG toolbar
```

Capture d’écran 2020-07-16 à 16 31 35

**Expected**
Toolbar is always visible when I edit text.

There's already a `sticky` option, but the documentation does not say what the default value is:
https://tinacms.org/docs/inline-editing/inline-wysiwyg#options

### PR DESCRIPTION
**Pull request by logan-anderson**
fixes #70

### CODE REVIEW

**Comment by DirtyF** [comment]
How did you compute the value in pixels? Asking as we could use `calc`  and CSS custom properties to compute it.

**Comment by logan-anderson** [comment]
> How did you compute the value in pixels? Asking as we could use `calc` and CSS custom properties to compute it.

Just the width of the toolbar

**Comment by DirtyF** [comment]
@logan-anderson can we add also a bit of padding? 
https://github.com/tinacms/tinacms.org/blob/e217a45a2408ff6fd713939885f886a342953a40/components/inline-wysiwyg.tsx#L18

**Comment by logan-anderson** [comment]
> @logan-anderson can we add also a bit of padding?
> https://github.com/tinacms/tinacms.org/blob/e217a45a2408ff6fd713939885f886a342953a40/components/inline-wysiwyg.tsx#L18

Yeah, we can and I like the idea of using calc! I pushed up those changes

**Pull request merged**
